[project]
authors = ["tdinapoli <tomas.dina98@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "tesis"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
pandas = ">=2.2.2,<3"
matplotlib = ">=3.9.2,<4"
ipympl = ">=0.9.4,<0.10"
dask = ">=2024.8.2,<2025"
scipy = ">=1.14.1,<2"
ipykernel = ">=6.29.5,<7"
