[project]
authors = ["tdinapoli <tomas.dina98@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "get_data_testing"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.5,<4"
paramiko = ">=3.4.1,<4"
scp = ">=0.15.0,<0.16"
